language: ruby
rvm:
  - 2.2.2
addons:
  code_climate:
    repo_token: 9c4e70ff8c17bd41eba56374ee5cf5fbd4600da4a3922fbe826d71ee8239836a
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "bundle exec rake test_app"
script:
  - "bundle exec rubocop"
  - "bundle exec rake"
notifications:
  email:
    - seb+github@sebashton.com
branches:
  only:
    - master
