sudo: false
cache: bundler
language: ruby
rvm:
  - 2.2.2
  - 2.3.0
before_install: gem update --remote bundler
before_script:
  - "bundle exec rake test_app"
script:
  - bundle exec rubocop
  - bundle exec rake
notifications:
  email:
    - seb+github@sebashton.com
branches:
  only:
    - master
addons:
  code_climate:
    repo_token: 9c4e70ff8c17bd41eba56374ee5cf5fbd4600da4a3922fbe826d71ee8239836a
